on:
  push:
  pull_request:

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        registry: [docker.pkg.github.com, ghcr.io]

    runs-on: ubuntu-latest

    env:
      IMAGE: ${{ matrix.registry }}/${{ github.repository }}/docker-ghcr-pull-request-tests:latest

    steps:
      - uses: actions/checkout@v2

      - name: Create a Dockerfile
        run: |
          echo 'FROM alpine' > Dockerfile
          echo 'ENTRYPOINT ["echo", "Hello from ${{ github.repository }}!"]' >> Dockerfile

      - name: Build image
        run: docker build . -t ${IMAGE,,} # lowercase IMAGE

      - name: Login to ${{ matrix.registry }}
        run: docker login ${{ matrix.registry }} -u token --password-stdin <<< ${{ github.token }}

      - name: Publish image
        run: docker push ${IMAGE,,} # lowercase IMAGE

      - name: Access a secret
        run: echo "Secret is ${{ secrets.SECRET }}"
